# Generated by Django 5.2.8 on 2025-11-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentsFinance', '0001_initial'),
        ('projects', '0001_initial'),
        ('refdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.project'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='documentsFinance.invoice'),
        ),
        migrations.AddField(
            model_name='quote',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='projects.project'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='quoteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documentsFinance.quote'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='taxRuleId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='refdata.taxrule'),
        ),
        migrations.AddField(
            model_name='quotesection',
            name='quoteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documentsFinance.quote'),
        ),
        migrations.AddField(
            model_name='subrent',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrents', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['quoteId', 'order'], name='idx_quoteline_quote_order'),
        ),
        migrations.AddConstraint(
            model_name='quoteline',
            constraint=models.UniqueConstraint(fields=('quoteId', 'order'), name='uniq_quoteline_order'),
        ),
        migrations.AddConstraint(
            model_name='quoteline',
            constraint=models.CheckConstraint(condition=models.Q(('order__isnull', True), ('order__gt', 0), _connector='OR'), name='check_quoteline_order_positive'),
        ),
        migrations.AddIndex(
            model_name='quotesection',
            index=models.Index(fields=['quoteId', 'order'], name='idx_quotesection_quote_order'),
        ),
        migrations.AddConstraint(
            model_name='quotesection',
            constraint=models.UniqueConstraint(fields=('quoteId', 'order'), name='uniq_quote_section_order'),
        ),
        migrations.AddConstraint(
            model_name='quotesection',
            constraint=models.CheckConstraint(condition=models.Q(('order__isnull', True), ('order__gt', 0), _connector='OR'), name='check_order_positive'),
        ),
    ]
