# Generated by Django 5.2.8 on 2025-11-11 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcrewneeds',
            name='assigned_crew',
            field=models.ManyToManyField(blank=True, related_name='assigned_needs', to='staff.crew'),
        ),
        migrations.AddField(
            model_name='projectcrewneeds',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_needs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectlogistics',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectnotes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notes', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='projects.project'),
        ),
    ]
