# Generated by Django 5.2.8 on 2025-11-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rates', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'crews',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('confirmed', models.BooleanField(default=False)),
                ('crewId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.crew')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'shifts',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('breaks', models.JSONField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('crewId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='staff.crew')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'timesheets',
            },
        ),
    ]
