# Generated by Django 5.2.8 on 2025-11-10 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('lines', models.JSONField(blank=True, null=True)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picklists', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'picklists',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityType', models.CharField(choices=[('asset', 'Asset'), ('case', 'Case')], max_length=20)),
                ('barcode', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('checkOut', 'Check Out'), ('checkIn', 'Check In')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='projects.project')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'scans',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('return', 'Return')], max_length=20)),
                ('plannedAt', models.DateTimeField()),
                ('actualAt', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=255, null=True)),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'shipments',
            },
        ),
    ]
