# Generated by Django 5.2.8 on 2025-11-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('refdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('entityType', models.CharField(choices=[('asset', 'Asset'), ('case', 'Case'), ('catalog_item', 'Catalog Item'), ('kit', 'Kit')], max_length=20)),
                ('entityId', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'barcodes',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('caseType', models.CharField(choices=[('flight', 'Flight Case'), ('pelican', 'Pelican Case'), ('road', 'Road Case'), ('soft', 'Soft Case'), ('other', 'Other')], max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contents', models.JSONField(blank=True, null=True)),
                ('upright_only', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'cases',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('sellable', models.BooleanField(default=False)),
                ('rentable', models.BooleanField(default=True)),
                ('isConsumable', models.BooleanField(default=False)),
                ('defaultRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.JSONField(blank=True, null=True)),
                ('upright_only', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog_items/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='company.company')),
                ('pricePolicy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='refdata.pricepolicy')),
            ],
            options={
                'verbose_name_plural': 'catalog items',
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.JSONField()),
                ('upright_only', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'kits',
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('warehouse', 'Warehouse'), ('truck', 'Truck'), ('shelf', 'Shelf')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stock_locations/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'stock locations',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='available', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='company.company')),
                ('catalogItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='equipment.catalogitem')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_assets', to='equipment.stocklocation')),
            ],
            options={
                'verbose_name_plural': 'assets',
            },
        ),
    ]
