# Generated by Django 5.2.8 on 2025-11-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255)),
                ('vatNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('billingAddress', models.TextField(blank=True, null=True)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
