# Generated by Django 5.2.8 on 2025-11-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='account',
            new_name='client',
        ),
    ]
