# Generated by Django 5.2.8 on 2025-11-10 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportedAt', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('description', models.TextField()),
                ('costRecovery', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('internal', 'Internal')], max_length=20)),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='equipment.asset')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'damages',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inspection', 'Inspection'), ('repair', 'Repair'), ('PAT', 'PAT')], max_length=20)),
                ('dueAt', models.DateTimeField()),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='equipment.asset')),
            ],
            options={
                'verbose_name_plural': 'maintenances',
            },
        ),
    ]
