// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/registration": {
    params: {};
  };
  "/calendar": {
    params: {};
  };
  "/catalog-items": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/registration" | "/calendar" | "/catalog-items";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/entery.tsx": {
    id: "routes/entery";
    page: "/registration";
  };
  "routes/registration.tsx": {
    id: "routes/registration";
    page: "/registration";
  };
  "routes/rent.tsx": {
    id: "routes/rent";
    page: "/calendar" | "/catalog-items";
  };
  "routes/calendar.tsx": {
    id: "routes/calendar";
    page: "/calendar";
  };
  "routes/catalog-items.tsx": {
    id: "routes/catalog-items";
    page: "/catalog-items";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/entery": typeof import("./app/routes/entery.tsx");
  "routes/registration": typeof import("./app/routes/registration.tsx");
  "routes/rent": typeof import("./app/routes/rent.tsx");
  "routes/calendar": typeof import("./app/routes/calendar.tsx");
  "routes/catalog-items": typeof import("./app/routes/catalog-items.tsx");
};