# Generated by Django 5.2.8 on 2025-11-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'availability views',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineId', models.CharField(max_length=100)),
                ('itemType', models.CharField(choices=[('catalog', 'Catalog Item'), ('kit', 'Kit'), ('asset', 'Asset')], max_length=10)),
                ('refId', models.IntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('dateFrom', models.DateTimeField()),
                ('dateTo', models.DateTimeField()),
                ('status', models.CharField(choices=[('hold', 'Hold'), ('reserved', 'Reserved'), ('checkedOut', 'Checked Out'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='hold', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'reservations',
            },
        ),
    ]
